-- Datos de ejemplo SINTÉTICOS (fechas, montos y volumen inventados).
-- No representan la facturación real del negocio.

USE BDSpa;
GO

-- CategoriaServicio
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (1, 'Cabello');
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (2, 'Complementos');
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (3, 'Depilación');
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (4, 'Estética Facial');
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (5, 'Pestañas y Cejas');
INSERT INTO CategoriaServicio (IDCategoria, NombreCategoria) VALUES (6, 'Uñas');

-- CatalogoServicio
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (1, 'Acrílicas', NULL, 42.0, 6);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (2, 'Manigel', NULL, 28.0, 6);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (3, 'Pedigel', NULL, 32.0, 6);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (4, 'Rubber', NULL, 36.0, 6);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (5, 'Retiro', NULL, 6.0, 6);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (6, 'Pigmentación de cejas', NULL, 18.0, 5);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (7, 'Lifting de pestañas', NULL, 24.0, 5);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (8, 'Pestañas clásicas', NULL, 26.0, 5);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (9, 'Depilación de cejas', NULL, 6.0, 5);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (10, 'Planchado capilar', NULL, 32.0, 1);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (11, 'Tinte', NULL, 68.0, 1);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (12, 'Corte de cabello', NULL, 12.0, 1);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (13, 'Botox capilar', NULL, 58.0, 1);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (14, 'Facial', NULL, 26.0, 4);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (15, 'Depilación de piernas', NULL, 11.0, 3);
INSERT INTO CatalogoServicio (IDServicio, NombreServicio, Descripcion, PrecioBase, IDCategoria) VALUES (16, 'Limpieza de pie', NULL, 14.0, 2);

-- Personal
INSERT INTO Personal (IDPersonal, Nombre, TipoPersonal, Estado) VALUES (1, 'Especialista Principal', 'Propietaria', 'Activo');

-- RegistroServicio (muestra sintética)
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (1, '2026-01-01', 1, 5, 1, 6.0, 6.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (2, '2026-01-01', 1, 4, 1, 36.0, 36.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (3, '2026-01-04', 1, 14, 1, 23.0, 23.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (4, '2026-01-04', 1, 4, 1, 44.0, 44.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (5, '2026-01-06', 1, 2, 1, 35.0, 35.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (6, '2026-01-06', 1, 10, 1, 33.0, 33.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (7, '2026-01-07', 1, 4, 1, 39.0, 39.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (8, '2026-01-10', 1, 16, 1, 16.0, 16.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (9, '2026-01-11', 1, 12, 1, 12.0, 12.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (10, '2026-01-11', 1, 8, 1, 23.0, 23.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (11, '2026-01-11', 1, 11, 1, 78.0, 78.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (12, '2026-01-13', 1, 6, 1, 21.0, 21.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (13, '2026-01-13', 1, 2, 1, 35.0, 35.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (14, '2026-01-14', 1, 11, 1, 77.0, 77.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (15, '2026-01-14', 1, 15, 1, 10.0, 10.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (16, '2026-01-17', 1, 15, 1, 11.0, 11.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (17, '2026-01-19', 1, 12, 1, 11.0, 11.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (18, '2026-01-19', 1, 10, 1, 29.0, 29.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (19, '2026-01-19', 1, 16, 1, 12.0, 12.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (20, '2026-01-20', 1, 14, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (21, '2026-01-21', 1, 13, 1, 72.0, 72.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (22, '2026-01-21', 1, 8, 1, 29.0, 29.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (23, '2026-01-22', 1, 9, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (24, '2026-01-23', 1, 5, 1, 7.0, 7.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (25, '2026-01-23', 1, 2, 1, 29.0, 29.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (26, '2026-01-24', 1, 13, 1, 59.0, 59.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (27, '2026-01-24', 1, 2, 1, 26.0, 26.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (28, '2026-01-26', 1, 2, 1, 25.0, 25.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (29, '2026-01-26', 1, 12, 1, 13.0, 13.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (30, '2026-01-27', 1, 5, 1, 7.0, 7.0, 'Domicilio', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (31, '2026-01-27', 1, 16, 1, 13.0, 13.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (32, '2026-01-28', 1, 16, 1, 15.0, 15.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (33, '2026-01-28', 1, 11, 1, 78.0, 78.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (34, '2026-01-28', 1, 1, 1, 39.0, 39.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (35, '2026-01-30', 1, 3, 1, 36.0, 36.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (36, '2026-01-31', 1, 12, 1, 14.0, 14.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (37, '2026-02-01', 1, 8, 1, 28.0, 28.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (38, '2026-02-01', 1, 7, 1, 28.0, 28.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (39, '2026-02-02', 1, 7, 1, 25.0, 25.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (40, '2026-02-04', 1, 16, 1, 13.0, 13.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (41, '2026-02-05', 1, 12, 1, 15.0, 15.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (42, '2026-02-05', 1, 8, 1, 27.0, 27.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (43, '2026-02-05', 1, 1, 1, 44.0, 44.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (44, '2026-02-08', 1, 7, 1, 25.0, 25.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (45, '2026-02-08', 1, 11, 1, 60.0, 60.0, 'Domicilio', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (46, '2026-02-09', 1, 13, 1, 67.0, 67.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (47, '2026-02-09', 1, 5, 1, 5.0, 5.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (48, '2026-02-09', 1, 5, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (49, '2026-02-10', 1, 5, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (50, '2026-02-10', 1, 4, 1, 38.0, 38.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (51, '2026-02-11', 1, 7, 1, 21.0, 21.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (52, '2026-02-12', 1, 9, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (53, '2026-02-12', 1, 12, 1, 15.0, 15.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (54, '2026-02-13', 1, 5, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (55, '2026-02-13', 1, 15, 1, 13.0, 13.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (56, '2026-02-14', 1, 6, 1, 16.0, 16.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (57, '2026-02-16', 1, 16, 1, 16.0, 16.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (58, '2026-02-16', 1, 8, 1, 24.0, 24.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (59, '2026-02-17', 1, 1, 1, 48.0, 48.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (60, '2026-02-17', 1, 7, 1, 27.0, 27.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (61, '2026-02-17', 1, 16, 1, 15.0, 15.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (62, '2026-02-18', 1, 7, 1, 28.0, 28.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (63, '2026-02-19', 1, 11, 1, 60.0, 60.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (64, '2026-02-19', 1, 10, 1, 37.0, 37.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (65, '2026-02-19', 1, 12, 1, 11.0, 11.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (66, '2026-02-20', 1, 4, 1, 36.0, 36.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (67, '2026-02-21', 1, 6, 1, 20.0, 20.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (68, '2026-02-22', 1, 7, 1, 24.0, 24.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (69, '2026-02-22', 1, 11, 1, 73.0, 73.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (70, '2026-02-23', 1, 10, 1, 34.0, 34.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (71, '2026-02-23', 1, 8, 1, 32.0, 32.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (72, '2026-02-25', 1, 9, 1, 7.0, 7.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (73, '2026-02-26', 1, 13, 1, 53.0, 53.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (74, '2026-02-27', 1, 3, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (75, '2026-02-27', 1, 3, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (76, '2026-02-28', 1, 3, 1, 35.0, 35.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (77, '2026-03-02', 1, 1, 1, 41.0, 41.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (78, '2026-03-02', 1, 9, 1, 7.0, 7.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (79, '2026-03-02', 1, 4, 1, 45.0, 45.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (80, '2026-03-03', 1, 10, 1, 34.0, 34.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (81, '2026-03-04', 1, 9, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (82, '2026-03-07', 1, 16, 1, 13.0, 13.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (83, '2026-03-08', 1, 16, 1, 15.0, 15.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (84, '2026-03-08', 1, 10, 1, 36.0, 36.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (85, '2026-03-09', 1, 13, 1, 72.0, 72.0, 'Domicilio', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (86, '2026-03-12', 1, 14, 1, 24.0, 24.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (87, '2026-03-13', 1, 8, 1, 29.0, 29.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (88, '2026-03-14', 1, 15, 1, 9.0, 9.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (89, '2026-03-15', 1, 8, 1, 22.0, 22.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (90, '2026-03-15', 1, 6, 1, 15.0, 15.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (91, '2026-03-16', 1, 8, 1, 27.0, 27.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (92, '2026-03-18', 1, 13, 1, 63.0, 63.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (93, '2026-03-19', 1, 3, 1, 35.0, 35.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (94, '2026-03-20', 1, 11, 1, 77.0, 77.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (95, '2026-03-20', 1, 5, 1, 5.0, 5.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (96, '2026-03-21', 1, 5, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (97, '2026-03-21', 1, 1, 1, 50.0, 50.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (98, '2026-03-22', 1, 3, 1, 28.0, 28.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (99, '2026-03-24', 1, 15, 1, 12.0, 12.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (100, '2026-03-24', 1, 8, 1, 27.0, 27.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (101, '2026-03-27', 1, 9, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (102, '2026-03-27', 1, 7, 1, 23.0, 23.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (103, '2026-03-27', 1, 13, 1, 51.0, 51.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (104, '2026-03-29', 1, 3, 1, 35.0, 35.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (105, '2026-03-30', 1, 5, 1, 5.0, 5.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (106, '2026-04-01', 1, 16, 1, 14.0, 14.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (107, '2026-04-02', 1, 4, 1, 45.0, 45.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (108, '2026-04-02', 1, 3, 1, 39.0, 39.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (109, '2026-04-02', 1, 15, 1, 14.0, 14.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (110, '2026-04-03', 1, 3, 1, 35.0, 35.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (111, '2026-04-04', 1, 5, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (112, '2026-04-04', 1, 4, 1, 41.0, 41.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (113, '2026-04-05', 1, 13, 1, 50.0, 50.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (114, '2026-04-05', 1, 15, 1, 11.0, 11.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (115, '2026-04-05', 1, 13, 1, 57.0, 57.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (116, '2026-04-06', 1, 13, 1, 52.0, 52.0, 'Domicilio', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (117, '2026-04-06', 1, 10, 1, 30.0, 30.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (118, '2026-04-08', 1, 14, 1, 30.0, 30.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (119, '2026-04-08', 1, 2, 1, 33.0, 33.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (120, '2026-04-09', 1, 9, 1, 6.0, 6.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (121, '2026-04-10', 1, 1, 1, 49.0, 49.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (122, '2026-04-10', 1, 7, 1, 27.0, 27.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (123, '2026-04-11', 1, 5, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (124, '2026-04-11', 1, 5, 1, 6.0, 6.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (125, '2026-04-11', 1, 9, 1, 7.0, 7.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (126, '2026-04-12', 1, 10, 1, 33.0, 33.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (127, '2026-04-13', 1, 3, 1, 30.0, 30.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (128, '2026-04-14', 1, 15, 1, 13.0, 13.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (129, '2026-04-15', 1, 7, 1, 23.0, 23.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (130, '2026-04-16', 1, 8, 1, 26.0, 26.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (131, '2026-04-16', 1, 1, 1, 48.0, 48.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (132, '2026-04-17', 1, 13, 1, 56.0, 56.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (133, '2026-04-18', 1, 5, 1, 7.0, 7.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (134, '2026-04-18', 1, 7, 1, 21.0, 21.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (135, '2026-04-19', 1, 14, 1, 32.0, 32.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (136, '2026-04-19', 1, 1, 1, 38.0, 38.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (137, '2026-04-19', 1, 16, 1, 17.0, 17.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (138, '2026-04-20', 1, 15, 1, 10.0, 10.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (139, '2026-04-20', 1, 4, 1, 44.0, 44.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (140, '2026-04-20', 1, 15, 1, 10.0, 10.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (141, '2026-04-21', 1, 8, 1, 28.0, 28.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (142, '2026-04-22', 1, 9, 1, 6.0, 6.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (143, '2026-04-25', 1, 7, 1, 24.0, 24.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (144, '2026-04-27', 1, 15, 1, 11.0, 11.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (145, '2026-04-28', 1, 16, 1, 15.0, 15.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (146, '2026-04-29', 1, 10, 1, 28.0, 28.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (147, '2026-04-29', 1, 14, 1, 23.0, 23.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (148, '2026-04-30', 1, 8, 1, 27.0, 27.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (149, '2026-04-30', 1, 12, 1, 13.0, 13.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (150, '2026-05-02', 1, 16, 1, 17.0, 17.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (151, '2026-05-03', 1, 15, 1, 10.0, 10.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (152, '2026-05-04', 1, 6, 1, 22.0, 22.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (153, '2026-05-04', 1, 2, 1, 34.0, 34.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (154, '2026-05-04', 1, 7, 1, 21.0, 21.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (155, '2026-05-06', 1, 13, 1, 60.0, 60.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (156, '2026-05-09', 1, 11, 1, 63.0, 63.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (157, '2026-05-10', 1, 2, 1, 27.0, 27.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (158, '2026-05-10', 1, 11, 1, 70.0, 70.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (159, '2026-05-10', 1, 3, 1, 32.0, 32.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (160, '2026-05-11', 1, 13, 1, 58.0, 58.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (161, '2026-05-12', 1, 3, 1, 28.0, 28.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (162, '2026-05-12', 1, 15, 1, 10.0, 10.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (163, '2026-05-14', 1, 8, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (164, '2026-05-14', 1, 2, 1, 29.0, 29.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (165, '2026-05-15', 1, 3, 1, 39.0, 39.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (166, '2026-05-17', 1, 11, 1, 83.0, 83.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (167, '2026-05-20', 1, 4, 1, 37.0, 37.0, 'Domicilio', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (168, '2026-05-21', 1, 9, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (169, '2026-05-21', 1, 16, 1, 13.0, 13.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (170, '2026-05-22', 1, 8, 1, 26.0, 26.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (171, '2026-05-24', 1, 13, 1, 67.0, 67.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (172, '2026-05-26', 1, 11, 1, 62.0, 62.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (173, '2026-05-26', 1, 3, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (174, '2026-05-26', 1, 16, 1, 17.0, 17.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (175, '2026-05-27', 1, 14, 1, 27.0, 27.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (176, '2026-05-29', 1, 10, 1, 31.0, 31.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (177, '2026-05-30', 1, 7, 1, 25.0, 25.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (178, '2026-05-31', 1, 7, 1, 24.0, 24.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (179, '2026-06-01', 1, 4, 1, 40.0, 40.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (180, '2026-06-02', 1, 8, 1, 31.0, 31.0, 'Domicilio', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (181, '2026-06-02', 1, 10, 1, 30.0, 30.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (182, '2026-06-02', 1, 7, 1, 29.0, 29.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (183, '2026-06-03', 1, 9, 1, 7.0, 7.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (184, '2026-06-03', 1, 12, 1, 11.0, 11.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (185, '2026-06-03', 1, 7, 1, 30.0, 30.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (186, '2026-06-04', 1, 1, 1, 49.0, 49.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (187, '2026-06-05', 1, 3, 1, 30.0, 30.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (188, '2026-06-07', 1, 4, 1, 42.0, 42.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (189, '2026-06-07', 1, 3, 1, 36.0, 36.0, 'Local', 'Efectivo', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (190, '2026-06-08', 1, 10, 1, 33.0, 33.0, 'Local', 'Yape', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (191, '2026-06-09', 1, 14, 1, 26.0, 26.0, 'Local', 'Mixto', NULL);
INSERT INTO RegistroServicio (IDRegistroServicio, Fecha, IDPersonal, IDServicio, Cantidad, Precio, Total, Modalidad, MetodoPago, Notas) VALUES (192, '2026-06-09', 1, 12, 1, 13.0, 13.0, 'Local', 'Efectivo', NULL);

GO